name: Release
on:
  push:
    tags:
      - 'ktsctl-v*'

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build ktsctl
      run: cargo build --release -p ktsctl
    - uses: actions/upload-artifact@v4
      with:
        name: ktsctl.Linux-x86_64
        path: target/release/ktsctl

  release-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build ktsctl
      run: cargo build --release -p ktsctl
    - uses: actions/upload-artifact@v4
      with:
        name: ktsctl.macOS-x86_64
        path: target/release/ktsctl
